export enum ControllerMessageType {
  PLAY = 'PLAY',
  PLAY_PAUSE = 'PLAY_PAUSE',
  PAUSE = 'PAUSE',
  NEXT = 'NEXT',
  PREVIOUS = 'PREVIOUS',
  TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE',
  TOGGLE_LIKE = 'TOGGLE_LIKE',
  TOGGLE_DISLIKE = 'TOGGLE_DISLIKE',
  SET_VOLUME = 'SET_VOLUME',
  SEEK_TO = 'SEEK_TO',
  START_TRACK = 'START_TRACK',
  PREPARE_FOR_SESSION = 'PREPARE_FOR_SESSION',
  SET_REPEAT_MODE = 'SET_REPEAT_MODE'
}
