export enum MusicControllerMessage {
  PLAY = 'PLAY',
  PLAY_PAUSE = 'PLAY_PAUSE',
  PAUSE = 'PAUSE',
  NEXT = 'NEXT',
  PREVIOUS = 'PREVIOUS',
  TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE',
  TOGGLE_LIKE = 'TOGGLE_LIKE',
  TOGGLE_DISLIKE = 'TOGGLE_DISLIKE',
  TOGGLE_MUTE = 'TOGGLE_MUTE',
  SET_VOLUME = 'SET_VOLUME',
  SEEK_TO = 'SEEK_TO',
  START_TRACK = 'START_TRACK',
  PREPARE_FOR_SESSION = 'PREPARE_FOR_SESSION',
  PREPARE_FOR_AUTOPLAY = 'PREPARE_FOR_AUTOPLAY',
  TOGGLE_REPEAT_MODE = 'TOGGLE_REPEAT_MODE',
  PLAY_QUEUE_TRACK = 'PLAY_QUEUE_TRACK',
  SEARCH_TRACKS = 'SEARCH_TRACKS'
}
