export enum SessionControllerMessage {
  END_SESSION = 'END_SESSION',
  LOCK_SESSION = 'LOCK_SESSION',
  UNLOCK_SESSION = 'UNLOCK_SESSION',
  KICK_LISTENER = 'KICK_LISTENER',
  GET_LISTENERS = 'GET_LISTENERS',
  GET_SESSION_DETAILS = 'GET_SESSION_DETAILS',
  PLAY_PAUSE_SESSION = 'PLAY_PAUSE_SESSION',
  PLAY_SESSION = 'PLAY_SESSION',
  PAUSE_SESSION = 'PAUSE_SESSION',
  NEXT_SESSION = 'NEXT_SESSION',
  PREVIOUS_SESSION = 'PREVIOUS_SESSION',
  TOGGLE_SESSION_REPEAT_MODE = 'TOGGLE_SESSION_REPEAT_MODE',
  SEEK_TO_SESSION = 'SEEK_TO_SESSION',
  UPDATE_SESSION_QUEUE_ITEM_POSITION = 'UPDATE_SESSION_QUEUE_ITEM_POSITION',
  REMOVE_SESSION_QUEUE_ITEM = 'REMOVE_SESSION_QUEUE_ITEM',
  ADD_SESSION_QUEUE_ITEM = 'ADD_SESSION_QUEUE_ITEM',
  GET_SESSION_QUEUE = 'GET_SESSION_QUEUE'
}
