export enum UiStateMessage {
  POPUP_OPENED = 'POPUP_OPENED',
  POPUP_CLOSED = 'POPUP_CLOSED',
  SIDEBAR_OPENED = 'SIDEBAR_OPENED',
  SIDEBAR_CLOSED = 'SIDEBAR_CLOSED',
  PIP_OPENED = 'PIP_OPENED',
  PIP_CLOSED = 'PIP_CLOSED'
}
